### ISSUE TITLE
Problem: cannot add new reference runs

### ISSUE THREAD

**Issue by sikler** [CMSTrackerDPG/certifier#104] opened 2022-03-12 08:44 UTC
Tried to add 348590 or 348683, but the response was that the run already exists as reference.
Weird. Could you help with that?

Thanks,
 Ferenc (offline SL)

**Comment by gbenelli** [comment] 2022-03-12 22:05
I can confirm I tried to add run 348590 for the shifter, and saw the error 
<img width="390" alt="image" src="https://user-images.githubusercontent.com/6179799/158036671-56931152-de15-4c4a-a64a-460d22d94449.png">

**Comment by nothingface0** [comment] 2022-03-14 10:00
From what I understand, this error does not mean that a specific reconstruction is already a reference. Instead, it denotes that the specific reconstruction has been already certified. 

Once a specific run reconstruction has been added to the Database, it cannot be set to be a reference, only _new_ entries can be given the `is_reference` attribute. 

You can see [here](https://certhelper.web.cern.ch/list/?options=on&runs_min=348590&runs_max=348590) that the `348590 (express)` is already certified and thus cannot be set to be a reference.

Is this how this part is supposed to work?

**Comment by sroychow** [comment] 2022-03-14 10:20
> Is this how this part is supposed to work?
On the contrary! A run can only be made a reference run only when it has been certified. Thus attribute should be an add-on feature.

**Comment by nothingface0** [comment] 2022-03-14 10:58
Ok, it's a bit confusing, but I think I can now explain how this part is build to work:
-  The **[Add Reference Run](https://certhelper.web.cern.ch/reference/)** page is intended to list reference runs and **add non-existent ones as reference**
- The **[Shift Leader View](https://certhelper.web.cern.ch/shiftleader/?runreconstruction__run__run_number__in=348590&runreconstruction__reconstruction=express&date__gte=2022-3-7&date__lte=2022-3-13)** allows Shift leaders to filter Run reconstructions and **promote existing ones to reference**
![image](https://user-images.githubusercontent.com/8612771/158158587-5bae4d37-8f1b-4988-ae6f-9dfcabcb4fa4.png)

I should update the documentation to explain this part more clearly

**Comment by sroychow** [comment] 2022-03-14 12:48
Hi @nothingface0 
Let me try to clear my doubt: here exsistent/non-exsistent is related to an entry in the database?

**Comment by nothingface0** [comment] 2022-03-14 13:01
@sroychow Sorry, yes. I updated my comment for clarity.

Judging from what you explained to me, there should only be only one procedure to add a reference run, and this should be:
1. Certify a new run
2. Promote it to reference via the Shift Leader View

This should prevent the confusion

**Comment by nothingface0** [comment] 2022-03-14 15:44
I have deployed a fix, as per @sroychow's suggestions. Please verify that it works as expected. Thanks!

**Comment by sroychow** [comment] 2022-03-14 16:41
Hi @nothingface0 thanks! now we can add a new run. But when we tried to add a run which was not certified, it crashed instead of issuing a warning.

**Comment by nothingface0** [comment] 2022-03-15 12:14
Fixes deployed, waiting for confirmation from you

**Comment by sroychow** [comment] 2022-03-15 16:26
The fix implemented resolves the issue. Closing it. Thanks @nothingface0

**Closed by sroychow** 2022-03-15 16:26 UTC
Labels: bug
